import type { WorldManifest, WorldDiff, ActionDef } from './manifest_schema';

/**
 * Compute a structural diff between two WorldManifests.
 *
 * All comparisons are deterministic and derived from manifest structure —
 * no prose generation, no AI commentary. The security_impact strings are
 * generated by simple condition checks on the structural changes.
 */
export function diffWorlds(
  oldManifest: WorldManifest,
  newManifest: WorldManifest
): WorldDiff {
  const actions_added: string[] = [];
  const actions_removed: string[] = [];
  const actions_changed: string[] = [];
  const rules_added: string[] = [];
  const rules_removed: string[] = [];
  const rules_changed: string[] = [];
  const trust_changes: string[] = [];
  const security_impact: string[] = [];

  // ---- Actions diff ----
  const oldActions = new Set(Object.keys(oldManifest.actions ?? {}));
  const newActions = new Set(Object.keys(newManifest.actions ?? {}));

  for (const a of newActions) {
    if (!oldActions.has(a)) {
      actions_added.push(a);
    }
  }
  for (const a of oldActions) {
    if (!newActions.has(a)) {
      actions_removed.push(a);
    }
  }
  for (const a of oldActions) {
    if (!newActions.has(a)) continue;
    const oldDef = oldManifest.actions[a];
    const newDef = newManifest.actions[a];
    const changes = describeActionChange(a, oldDef, newDef);
    if (changes.length > 0) {
      actions_changed.push(...changes);
    }
  }

  // ---- Rules diff ----
  const oldRules = new Map(
    (oldManifest.rules ?? []).map((r) => [r.id, r])
  );
  const newRules = new Map(
    (newManifest.rules ?? []).map((r) => [r.id, r])
  );

  for (const [id] of newRules) {
    if (!oldRules.has(id)) {
      rules_added.push(id);
    }
  }
  for (const [id] of oldRules) {
    if (!newRules.has(id)) {
      rules_removed.push(id);
    }
  }
  for (const [id, oldRule] of oldRules) {
    if (!newRules.has(id)) continue;
    const newRule = newRules.get(id)!;
    if (
      JSON.stringify(oldRule.if) !== JSON.stringify(newRule.if) ||
      JSON.stringify(oldRule.then) !== JSON.stringify(newRule.then)
    ) {
      rules_changed.push(
        `${id}: was {then: ${JSON.stringify(oldRule.then)}} → now {then: ${JSON.stringify(newRule.then)}}`
      );
    }
  }

  // ---- Trust source diff ----
  const oldSources = new Set(Object.keys(oldManifest.trust_sources ?? {}));
  const newSources = new Set(Object.keys(newManifest.trust_sources ?? {}));

  for (const s of newSources) {
    if (!oldSources.has(s)) {
      trust_changes.push(`"${s}" added (trust: ${newManifest.trust_sources[s].trust})`);
    }
  }
  for (const s of oldSources) {
    if (!newSources.has(s)) {
      trust_changes.push(`"${s}" removed`);
    }
  }
  for (const s of oldSources) {
    if (!newSources.has(s)) continue;
    const oldDef = oldManifest.trust_sources[s];
    const newDef = newManifest.trust_sources[s];
    if (oldDef.trust !== newDef.trust) {
      trust_changes.push(`"${s}" trust changed: ${oldDef.trust} → ${newDef.trust}`);
    }
    if (oldDef.default_taint !== newDef.default_taint) {
      trust_changes.push(
        `"${s}" default_taint changed: ${oldDef.default_taint} → ${newDef.default_taint}`
      );
    }
  }

  // ---- Security impact strings ----
  // Actions broadened (more sources allowed)
  for (const a of oldActions) {
    if (!newActions.has(a)) continue;
    const oldDef = oldManifest.actions[a];
    const newDef = newManifest.actions[a];
    const gained = newDef.allowed_from.filter((s) => !oldDef.allowed_from.includes(s));
    const lost = oldDef.allowed_from.filter((s) => !newDef.allowed_from.includes(s));
    if (gained.length > 0) {
      security_impact.push(
        `"${a}" now allowed from: ${gained.join(', ')} (previously not allowed)`
      );
    }
    if (lost.length > 0) {
      security_impact.push(
        `"${a}" no longer allowed from: ${lost.join(', ')}`
      );
    }
  }

  // Rules that were blocking and are now removed
  for (const removedId of rules_removed) {
    const oldRule = oldRules.get(removedId)!;
    if (oldRule.then?.decision === 'deny' || oldRule.then?.decision === 'ask') {
      security_impact.push(
        `Rule "${removedId}" removed (was: ${oldRule.then.decision}${oldRule.if?.action ? ` on ${oldRule.if.action}` : ''})`
      );
    }
  }

  // Rules whose decision became less restrictive
  for (const [id, oldRule] of oldRules) {
    if (!newRules.has(id)) continue;
    const newRule = newRules.get(id)!;
    const oldDecision = oldRule.then?.decision;
    const newDecision = newRule.then?.decision;
    if (oldDecision === 'deny' && newDecision === 'ask') {
      security_impact.push(
        `Rule "${id}" relaxed: deny → ask${oldRule.if?.action ? ` (action: ${oldRule.if.action})` : ''}`
      );
    }
    if (
      (oldDecision === 'deny' || oldDecision === 'ask') &&
      newDecision === 'allow'
    ) {
      security_impact.push(
        `Rule "${id}" relaxed: ${oldDecision} → allow${oldRule.if?.action ? ` (action: ${oldRule.if.action})` : ''}`
      );
    }
    if (oldDecision === 'ask' && newDecision === 'deny') {
      security_impact.push(
        `Rule "${id}" tightened: ask → deny${oldRule.if?.action ? ` (action: ${oldRule.if.action})` : ''}`
      );
    }
  }

  // Trust downgrades
  for (const s of oldSources) {
    if (!newSources.has(s)) continue;
    if (
      oldManifest.trust_sources[s].trust === 'trusted' &&
      newManifest.trust_sources[s].trust === 'untrusted'
    ) {
      security_impact.push(`Source "${s}" downgraded: trusted → untrusted`);
    }
  }

  return {
    actions_added,
    actions_removed,
    actions_changed,
    rules_added,
    rules_removed,
    rules_changed,
    trust_changes,
    security_impact
  };
}

function describeActionChange(
  name: string,
  oldDef: ActionDef,
  newDef: ActionDef
): string[] {
  const changes: string[] = [];
  if (oldDef.effect !== newDef.effect) {
    changes.push(`"${name}" effect changed: ${oldDef.effect} → ${newDef.effect}`);
  }
  const oldSources = [...oldDef.allowed_from].sort();
  const newSources = [...newDef.allowed_from].sort();
  if (JSON.stringify(oldSources) !== JSON.stringify(newSources)) {
    changes.push(
      `"${name}" allowed_from changed: [${oldSources.join(', ')}] → [${newSources.join(', ')}]`
    );
  }
  return changes;
}

/**
 * Returns true if there are no differences between the two manifests.
 */
export function isNoDiff(diff: WorldDiff): boolean {
  return (
    diff.actions_added.length === 0 &&
    diff.actions_removed.length === 0 &&
    diff.actions_changed.length === 0 &&
    diff.rules_added.length === 0 &&
    diff.rules_removed.length === 0 &&
    diff.rules_changed.length === 0 &&
    diff.trust_changes.length === 0
  );
}
