"""
operator_models.py — Operator-facing data models for SYS-4A.

Frozen dataclasses only; no logic, no I/O.  All fields are JSON-serializable.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional


# ---------------------------------------------------------------------------
# World lifecycle
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class WorldActivationRecord:
    """
    A single entry in the world activation history.

    Append-only; one record per activate_world or rollback_world call.
    """

    activation_id: str
    world_id: str
    version: str
    previous_world_id: Optional[str]
    previous_version: Optional[str]
    activated_at: str
    activated_by: Optional[str] = field(default=None)
    reason: Optional[str] = field(default=None)
    is_rollback: bool = field(default=False)

    def to_dict(self) -> dict[str, Any]:
        return {
            "activation_id": self.activation_id,
            "world_id": self.world_id,
            "version": self.version,
            "previous_world_id": self.previous_world_id,
            "previous_version": self.previous_version,
            "activated_at": self.activated_at,
            "activated_by": self.activated_by,
            "reason": self.reason,
            "is_rollback": self.is_rollback,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "WorldActivationRecord":
        return cls(
            activation_id=data["activation_id"],
            world_id=data["world_id"],
            version=str(data["version"]),
            previous_world_id=data.get("previous_world_id"),
            previous_version=data.get("previous_version"),
            activated_at=data["activated_at"],
            activated_by=data.get("activated_by"),
            reason=data.get("reason"),
            is_rollback=bool(data.get("is_rollback", False)),
        )


# ---------------------------------------------------------------------------
# Program operator surface
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ProgramSummary:
    """Operator-facing summary of a reviewed program."""

    program_id: str
    status: str
    world_version_at_creation: str
    compatible_with_active_world: Optional[bool]
    last_replay_verdict: Optional[str] = field(default=None)

    def to_dict(self) -> dict[str, Any]:
        return {
            "program_id": self.program_id,
            "status": self.status,
            "world_version_at_creation": self.world_version_at_creation,
            "compatible_with_active_world": self.compatible_with_active_world,
            "last_replay_verdict": self.last_replay_verdict,
        }


# ---------------------------------------------------------------------------
# Scenario operator surface
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ScenarioSummary:
    """Operator-facing summary of a scenario."""

    scenario_id: str
    program_id: Optional[str]
    worlds: tuple[dict[str, str], ...]
    last_run_at: Optional[str] = field(default=None)
    last_diverged: Optional[bool] = field(default=None)

    def to_dict(self) -> dict[str, Any]:
        return {
            "scenario_id": self.scenario_id,
            "program_id": self.program_id,
            "worlds": list(self.worlds),
            "last_run_at": self.last_run_at,
            "last_diverged": self.last_diverged,
        }


# ---------------------------------------------------------------------------
# Activation impact report
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ProgramImpact:
    """Impact on a single program from a proposed world activation."""

    program_id: str
    current_compatible: Optional[bool]
    target_compatible: bool
    summary: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "program_id": self.program_id,
            "current_compatible": self.current_compatible,
            "target_compatible": self.target_compatible,
            "summary": self.summary,
        }


@dataclass(frozen=True)
class ScenarioImpact:
    """Impact on a single scenario from a proposed world activation."""

    scenario_id: str
    summary: str
    divergence_expected: bool

    def to_dict(self) -> dict[str, Any]:
        return {
            "scenario_id": self.scenario_id,
            "summary": self.summary,
            "divergence_expected": self.divergence_expected,
        }


@dataclass(frozen=True)
class ActivationImpactReport:
    """
    Deterministic impact report for a proposed world activation.

    Generated by WorldOperatorService.preview_activation_impact().
    """

    target_world: dict[str, str]
    current_world: Optional[dict[str, str]]
    affected_programs: tuple[ProgramImpact, ...]
    affected_scenarios: tuple[ScenarioImpact, ...]
    totals: dict[str, int]
    generated_at: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "target_world": self.target_world,
            "current_world": self.current_world,
            "affected_programs": [p.to_dict() for p in self.affected_programs],
            "affected_scenarios": [s.to_dict() for s in self.affected_scenarios],
            "totals": dict(self.totals),
            "generated_at": self.generated_at,
        }
